### ISSUE TITLE
[rosrun] Couldn't find executable named issue_yaml.py...

### ISSUE THREAD

**Issue by MartinaRuocco** [betab0t/ros_python3_issues#1]
Hi! Thanks for your article and thanks for your ROS package!
I followed the steps in the readme but after the rosrun of the issue_yaml.py I get this message:

`[rosrun] Couldn't find executable named issue_yaml.py below /home/user/catkin_ws/src/ros_python3_issues 
Found the following, but they're either not files, or not executable:   /home/user/catkin_ws/src/ros_python3_issues/src/issue_yaml.py`

Any idea on how to solve this? 
PS: I'm a ROS beginner :)
Many thanks in advance!!

**Comment by FatihcanUslu** [comment]
i am having the same problem did you figured out how to solve it ?
